# Generated by Django 5.2.2 on 2026-06-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariantimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='duration',
            field=models.CharField(blank=True, choices=[('12', '12 Months'), ('24', '24 Months'), ('36', '36 Months'), ('60', '60 Months'), ('payg', 'Pay As You Go')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'duration', 'storage', 'colour', 'condition')},
        ),
    ]
