# Generated by Django 6.0 on 2026-06-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='btorder',
            new_name='orders_btor_email_292749_idx',
            old_name='orders_bt_email_45d3eb_idx',
        ),
        migrations.RenameIndex(
            model_name='btorder',
            new_name='orders_btor_bt_stat_790410_idx',
            old_name='orders_bt_bt_stat_566ef7_idx',
        ),
        migrations.RenameIndex(
            model_name='btorder',
            new_name='orders_btor_local_s_d88fd5_idx',
            old_name='orders_bt_local_s_391a4b_idx',
        ),
        migrations.RenameIndex(
            model_name='btorderevent',
            new_name='orders_btor_externa_352f18_idx',
            old_name='orders_bt_externa_5f051f_idx',
        ),
    ]
