# Generated by Django 6.0.6 on 2026-06-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orders_bt_email_45d3eb_idx_orders_btor_email_292749_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='btorder',
            name='data_allowance',
            field=models.CharField(blank=True, help_text="EE mobile only, e.g. '50GB'.", max_length=64),
        ),
        migrations.AddField(
            model_name='btorder',
            name='mail_error',
            field=models.TextField(blank=True, help_text='SMTP error if the email failed to send.'),
        ),
        migrations.AddField(
            model_name='btorder',
            name='mail_required',
            field=models.BooleanField(default=False, help_text='True for EE mobile / landline orders, which notify orders@zoikotelecom.com.'),
        ),
        migrations.AddField(
            model_name='btorder',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='btorder',
            name='mail_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='btorder',
            name='mail_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Mail not send')], db_index=True, default='not_required', max_length=16),
        ),
        migrations.AddField(
            model_name='btorder',
            name='order_type',
            field=models.CharField(choices=[('broadband', 'Broadband'), ('ee_mobile', 'EE Mobile'), ('landline', 'Landline')], db_index=True, default='broadband', help_text='Product family: broadband (BT Wholesale), EE mobile, or landline.', max_length=16),
        ),
        migrations.AddField(
            model_name='btorder',
            name='sim_type',
            field=models.CharField(blank=True, help_text="EE mobile only: 'eSIM' | 'pSIM'.", max_length=16),
        ),
        migrations.AddIndex(
            model_name='btorder',
            index=models.Index(fields=['order_type', '-created_at'], name='orders_btor_order_t_a93b54_idx'),
        ),
    ]
