# Generated by Django 6.0.6 on 2026-06-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_btorder_data_allowance_btorder_mail_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EEMobileOrder',
            fields=[
            ],
            options={
                'verbose_name': 'EE Mobile order',
                'verbose_name_plural': 'EE Mobile orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.btorder',),
        ),
        migrations.CreateModel(
            name='LandlineOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Landline order',
                'verbose_name_plural': 'Landline orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.btorder',),
        ),
    ]
