# Generated by Django 6.0.6 on 2026-07-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_eemobileorder_landlineorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Accessories order',
                'verbose_name_plural': 'Accessories orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.btorder',),
        ),
        migrations.AlterField(
            model_name='btorder',
            name='order_type',
            field=models.CharField(choices=[('broadband', 'Broadband'), ('ee_mobile', 'EE Mobile'), ('landline', 'Landline'), ('accessories', 'Accessories')], db_index=True, default='broadband', help_text='Product family: broadband (BT Wholesale), EE mobile, or landline.', max_length=16),
        ),
    ]
