# Generated by Django 6.0.6 on 2026-07-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_accessoriesorder_alter_btorder_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneEquipmentOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Phone & Equipment order',
                'verbose_name_plural': 'Phone & Equipment orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.btorder',),
        ),
        migrations.AlterField(
            model_name='btorder',
            name='order_type',
            field=models.CharField(choices=[('broadband', 'Broadband'), ('ee_mobile', 'EE Mobile'), ('landline', 'Landline'), ('accessories', 'Accessories'), ('phone_equipment', 'Phone Equipment')], db_index=True, default='broadband', help_text='Product family: broadband (BT Wholesale), EE mobile, or landline.', max_length=16),
        ),
    ]
