# Generated by Django 6.0.6 on 2026-07-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_phoneequipmentorder_alter_btorder_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLandlineOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Business Landline order',
                'verbose_name_plural': 'Business Landline orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.btorder',),
        ),
        migrations.AlterField(
            model_name='btorder',
            name='order_type',
            field=models.CharField(choices=[('broadband', 'Broadband'), ('ee_mobile', 'EE Mobile'), ('landline', 'Landline'), ('business_landline', 'Business Landline'), ('accessories', 'Accessories'), ('phone_equipment', 'Phone Equipment')], db_index=True, default='broadband', help_text='Product family: broadband (BT Wholesale), EE mobile, landline, business landline, accessories, or phone equipment.', max_length=32),
        ),
    ]
