# Generated by Django 5.2.2 on 2026-07-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_businesslandlineorder_alter_btorder_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='btorder',
            name='confirmation_error',
            field=models.TextField(blank=True, help_text='SMTP error if the customer confirmation failed to send.'),
        ),
        migrations.AddField(
            model_name='btorder',
            name='confirmation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='btorder',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='btorder',
            name='confirmation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped (no email)')], db_index=True, default='pending', max_length=16),
        ),
    ]
