# Generated by Django 6.0 on 2026-06-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('services', models.JSONField(default=list)),
                ('declaration_one', models.BooleanField(default=False)),
                ('declaration_two', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=255)),
                ('digital_signature', models.CharField(max_length=255)),
                ('signed_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reseller_form',
                'ordering': ['-created_at'],
            },
        ),
    ]
