# Generated by Django 6.0 on 2026-06-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contactmessage_id'),
        ('contact', '0005_alter_contactmessage_phone'),
    ]

    operations = [
    ]
