"""
Models for BT Wholesale orders.

One BTOrder row per checkout. The full Next.js / BT payload is stored as
JSON blobs (`cart_raw`, `bt_response_raw`, etc.) so nothing is lost; the
denormalised columns alongside them exist for indexed lookups and admin
filtering. BTOrderEvent appends one row per state change (initial creation,
BT webhook notifications, manual edits) — never overwritten.
"""

from __future__ import annotations

from django.db import models
from django.utils import timezone

# ─── Status / state choices ───────────────────────────────────────────────────

class LocalStatus(models.TextChoices):
    """Our local lifecycle, derived from the BT response on creation."""
    CREATED = "created", "Created"           # BT returned 201
    PENDING = "pending", "Pending"           # BT returned 202 (async)
    UNKNOWN = "unknown", "Unknown"           # BT returned 2xx but not 201/202
    FAILED  = "failed",  "Failed"            # BT call failed but we still want a record

class BTOrderState(models.TextChoices):
    """BT lifecycle states delivered via the webhook (API 8)."""
    ACKNOWLEDGED = "acknowledged", "Acknowledged"
    IN_PROGRESS  = "inProgress",   "In progress"
    HELD         = "held",         "Held"
    COMPLETED    = "completed",    "Completed"
    REFUSED      = "refused",      "Refused"
    CANCELLED    = "cancelled",    "Cancelled"
    REJECTED     = "rejected",     "Rejected"


class PaymentMethod(models.TextChoices):
    STRIPE = "stripe", "Stripe"
    OTHER  = "other",  "Other"


class OrderType(models.TextChoices):
    """Which product family this order belongs to."""
    BROADBAND       = "broadband",       "Broadband"
    EE_MOBILE       = "ee_mobile",        "EE Mobile"
    LANDLINE        = "landline",         "Landline"
    BUSINESS_LANDLINE = "business_landline", "Business Landline"
    ACCESSORIES     = "accessories",      "Accessories"
    PHONE_EQUIPMENT = "phone_equipment",  "Phone Equipment"


class MailStatus(models.TextChoices):
    """Notification-email state for EE mobile / landline orders."""
    NOT_REQUIRED = "not_required", "Not required"   # broadband — no email
    PENDING      = "pending",      "Pending"         # required, not yet attempted
    SENT         = "sent",         "Sent"
    FAILED       = "failed",       "Mail not send"   # attempted, SMTP failed


# ─── Main order ───────────────────────────────────────────────────────────────

class BTOrder(models.Model):
    # ── Identity ────────────────────────────────────────────────────────────
    order_type = models.CharField(
        max_length=32,
        choices=OrderType.choices,
        default=OrderType.BROADBAND,
        db_index=True,
        help_text="Product family: broadband (BT Wholesale), EE mobile, landline, business landline, accessories, or phone equipment.",
    )
    external_id = models.CharField(
        max_length=128,
        unique=True,
        db_index=True,
        help_text="Generated by Next.js. Format: WC-{timestamp}-{nnnnn}. "
                  "Used to correlate webhook events back to this row.",
    )
    bt_order_id = models.CharField(
        max_length=128,
        blank=True,
        db_index=True,
        help_text="BT's order id (from 201 response) — or PENDING-{external_id} "
                  "while a 202 order is being acknowledged.",
    )

    # ── Status / state ──────────────────────────────────────────────────────
    local_status = models.CharField(
        max_length=16,
        choices=LocalStatus.choices,
        default=LocalStatus.CREATED,
        db_index=True,
    )
    bt_state = models.CharField(
        max_length=32,
        choices=BTOrderState.choices,
        blank=True,
        db_index=True,
        help_text="Latest state reported by BT (via webhook). Initially empty.",
    )
    error_message = models.TextField(
        blank=True,
        help_text="Most recent BT or internal error. Cleared on successful state advance.",
    )

    # ── Billing contact (denormalised for search/admin) ─────────────────────
    first_name    = models.CharField(max_length=120)
    last_name     = models.CharField(max_length=120, blank=True)
    email         = models.EmailField(db_index=True)
    phone         = models.CharField(max_length=40, blank=True)
    company_name  = models.CharField(max_length=200, blank=True)

    # Billing address (denormalised)
    billing_street       = models.CharField(max_length=255, blank=True)
    billing_house_number = models.CharField(max_length=40,  blank=True)
    billing_city         = models.CharField(max_length=120, blank=True)
    billing_region       = models.CharField(max_length=120, blank=True)
    billing_state        = models.CharField(max_length=120, blank=True)
    billing_zip          = models.CharField(max_length=20,  blank=True)

    # ── Service / install address (BT-side) ─────────────────────────────────
    service_address_id   = models.CharField(
        max_length=64,
        blank=True,
        db_index=True,
        help_text="Openreach NAD id (A...) from the localStorage cart.",
    )
    service_postcode     = models.CharField(max_length=20,  blank=True, db_index=True)
    service_city         = models.CharField(max_length=120, blank=True)
    service_street_name  = models.CharField(max_length=255, blank=True)
    service_street_nr    = models.CharField(max_length=40,  blank=True)
    service_district     = models.CharField(max_length=8,   blank=True)
    service_qualifier    = models.CharField(max_length=32,  blank=True)

    # ── Product (denormalised summary; full data lives in cart_raw) ─────────
    product_name           = models.CharField(max_length=255, blank=True)
    product_offering_id    = models.CharField(max_length=64,  blank=True, db_index=True)
    contract_term          = models.CharField(max_length=32,  blank=True,
                                              help_text="e.g. 24-months")
    download_speed         = models.CharField(max_length=16,  blank=True)
    upload_speed           = models.CharField(max_length=16,  blank=True)

    # ── EE mobile extras (denormalised; full data lives in cart_raw) ────────
    data_allowance = models.CharField(max_length=64, blank=True,
                                       help_text="EE mobile only, e.g. '50GB'.")
    sim_type       = models.CharField(max_length=16, blank=True,
                                       help_text="EE mobile only: 'eSIM' | 'pSIM'.")

    # ── Notification email (EE mobile / landline only) ──────────────────────
    mail_required = models.BooleanField(
        default=False,
        help_text="True for EE mobile / landline orders, which notify orders@zoikotelecom.com.",
    )
    mail_sent    = models.BooleanField(default=False)
    mail_status  = models.CharField(
        max_length=16,
        choices=MailStatus.choices,
        default=MailStatus.NOT_REQUIRED,
        db_index=True,
    )
    mail_error   = models.TextField(blank=True, help_text="SMTP error if the email failed to send.")
    mail_sent_at = models.DateTimeField(null=True, blank=True)

    # ── Appointment ─────────────────────────────────────────────────────────
    appointment_id    = models.CharField(max_length=64, blank=True, db_index=True)
    appointment_start = models.DateTimeField(null=True, blank=True)
    appointment_end   = models.DateTimeField(null=True, blank=True)

    # ── Money ───────────────────────────────────────────────────────────────
    subtotal = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total    = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    currency = models.CharField(max_length=8, default="GBP")

    coupon_code     = models.CharField(max_length=64, blank=True)
    coupon_type     = models.CharField(max_length=16, blank=True,
                                       help_text="percentage|flat")
    coupon_discount = models.CharField(max_length=32, blank=True)

    # ── Payment & consent ───────────────────────────────────────────────────
    payment_method   = models.CharField(
        max_length=16,
        choices=PaymentMethod.choices,
        default=PaymentMethod.STRIPE,
    )
    agreed_to_terms  = models.BooleanField(default=False)
    client_created_at = models.DateTimeField(
        null=True, blank=True,
        help_text="`createdAt` sent by the browser — kept for audit.",
    )

    # ── Raw blobs (audit / replay) ──────────────────────────────────────────
    cart_raw             = models.JSONField(default=list, blank=True)
    service_address_raw  = models.JSONField(default=dict, blank=True)
    billing_address_raw  = models.JSONField(default=dict, blank=True)
    shipping_address_raw = models.JSONField(default=dict, blank=True)
    totals_raw           = models.JSONField(default=dict, blank=True)
    coupon_raw           = models.JSONField(default=dict, blank=True, null=True)

    # Everything BT returned (the `btData` field from the Next.js BT route)
    bt_response_raw      = models.JSONField(default=dict, blank=True)
    # Raw envelope received by this endpoint (full request body)
    request_payload_raw  = models.JSONField(default=dict, blank=True)

    # ── Server timestamps ───────────────────────────────────────────────────
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["email", "-created_at"]),
            models.Index(fields=["bt_state", "-created_at"]),
            models.Index(fields=["local_status", "-created_at"]),
            models.Index(fields=["order_type", "-created_at"]),
        ]

    def __str__(self) -> str:  # pragma: no cover - admin label
        return f"{self.external_id} ({self.email})"

    # Convenience for the webhook handler
    def advance_state(self, new_state: str, error_messages: list | None = None) -> None:
        self.bt_state = new_state
        if error_messages:
            self.error_message = "\n".join(
                f"[{m.get('subCode', '')}] {m.get('reason', '')}: {m.get('message', '')}".strip()
                for m in error_messages if isinstance(m, dict)
            )
        else:
            # Clear stale errors on a successful state advance
            if new_state in (BTOrderState.COMPLETED, BTOrderState.IN_PROGRESS):
                self.error_message = ""
        self.save(update_fields=["bt_state", "error_message", "updated_at"])


# ─── Append-only event log ───────────────────────────────────────────────────

class BTOrderEvent(models.Model):
    """One row per state change. Never overwritten — used for audit and replay."""

    class Source(models.TextChoices):
        CHECKOUT  = "checkout",  "Checkout (initial)"
        WEBHOOK   = "webhook",   "BT webhook"
        MANUAL    = "manual",    "Manual"
        SYSTEM    = "system",    "System"

    order = models.ForeignKey(
        BTOrder,
        on_delete=models.CASCADE,
        related_name="events",
        null=True,
        blank=True,
        help_text="Null only for orphaned webhooks (BT sent us an externalId we don't have).",
    )
    source        = models.CharField(max_length=16, choices=Source.choices, default=Source.SYSTEM)
    event_type    = models.CharField(
        max_length=64,
        blank=True,
        help_text="e.g. ProductOrderStateChangeEvent, ProductOrderCreationNotification.",
    )
    bt_event_id   = models.CharField(max_length=128, blank=True, db_index=True)
    state         = models.CharField(max_length=32, blank=True)
    sub_code      = models.CharField(max_length=32, blank=True)
    message       = models.TextField(blank=True)
    payload_raw   = models.JSONField(default=dict, blank=True)
    received_at   = models.DateTimeField(default=timezone.now, db_index=True)
    external_id   = models.CharField(
        max_length=128,
        blank=True,
        db_index=True,
        help_text="Stored even when `order` is null — lets us reconcile orphaned webhooks "
                  "if the order is created later.",
    )

    class Meta:
        ordering = ["-received_at"]
        indexes = [
            models.Index(fields=["external_id", "-received_at"]),
        ]

    def __str__(self) -> str:  # pragma: no cover
        return f"{self.event_type or self.state} @ {self.received_at:%Y-%m-%d %H:%M}"


# ─── Proxy models ───────────────────────────────────────────────────────────────
#
# All orders live in the single BTOrder table (distinguished by `order_type`).
# These proxies create separate admin sections — Broadband / EE Mobile / Landline
# — without a second table or any schema change. Each proxy admin filters its
# queryset to its own order_type (see admin.py).

class EEMobileOrder(BTOrder):
    class Meta:
        proxy = True
        verbose_name = "EE Mobile order"
        verbose_name_plural = "EE Mobile orders"


class LandlineOrder(BTOrder):
    class Meta:
        proxy = True
        verbose_name = "Landline order"
        verbose_name_plural = "Landline orders"


class BusinessLandlineOrder(BTOrder):
    class Meta:
        proxy = True
        verbose_name = "Business Landline order"
        verbose_name_plural = "Business Landline orders"


class AccessoriesOrder(BTOrder):
    class Meta:
        proxy = True
        verbose_name = "Accessories order"
        verbose_name_plural = "Accessories orders"


class PhoneEquipmentOrder(BTOrder):
    class Meta:
        proxy = True
        verbose_name = "Phone & Equipment order"
        verbose_name_plural = "Phone & Equipment orders"