# Generated by Django 6.0 on 2026-06-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundle_requests', '0002_bundlerequest_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlerequest',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
