# Generated by Django 5.2.2 on 2026-06-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundle_requests', '0002_bundlerequest_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlerequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bundlerequest',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
