# Generated by Django 5.2.2 on 2026-06-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundle_requests', '0003_alter_bundlerequest_id_alter_bundlerequest_phone'),
        ('bundle_requests', '0003_alter_bundlerequest_phone'),
    ]

    operations = [
    ]
