# Generated by Django 6.0 on 2026-06-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('service_interest', models.CharField(choices=[('business_broadband', 'Business Broadband'), ('leased_line', 'Leased Line'), ('voip', 'VoIP'), ('business_mobile', 'Business Mobile'), ('connectivity', 'Connectivity'), ('other', 'Other')], max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
