# Generated by Django 6.0 on 2026-06-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesssolutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssolution',
            name='service_interest',
            field=models.CharField(choices=[('business_mobile', 'Business Mobile'), ('business_broadband', 'Business Broadband'), ('hosted_voice', 'Hosted Voice'), ('full_fibre', 'Full Fibre'), ('number_porting', 'Number Porting'), ('managed_connectivity', 'Managed Connectivity'), ('other', 'Other')], max_length=100),
        ),
    ]
