# Generated by Django 6.0 on 2026-05-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(max_length=150)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('services_of_interest', models.JSONField(default=list)),
                ('full_name', models.CharField(max_length=150)),
                ('digital_signature', models.CharField(max_length=150)),
                ('signature_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Reseller Application',
                'verbose_name_plural': 'Reseller Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
